/**
 * Skill: generate-tests
 * Generates unit tests for a given TypeScript source file or function.
 * Uses the Stitch skill interface to integrate with the broader pipeline.
 */

import * as fs from "fs";
import * as path from "path";

export interface GenerateTestsInput {
  /** The TypeScript source code to generate tests for */
  sourceCode: string;
  /** Optional file path for context (used to infer module name) */
  filePath?: string;
  /** Testing framework to target */
  framework?: "jest" | "vitest" | "mocha";
  /** Whether to include edge case tests */
  includeEdgeCases?: boolean;
}

export interface GenerateTestsOutput {
  /** The generated test file content */
  testCode: string;
  /** Suggested filename for the test file */
  testFileName: string;
  /** Number of test cases generated */
  testCount: number;
}

/**
 * Extracts exported function signatures from TypeScript source code.
 */
function extractExports(sourceCode: string): string[] {
  const exportPattern =
    /export\s+(?:async\s+)?function\s+(\w+)\s*\(([^)]*?)\)/g;
  const exports: string[] = [];
  let match: RegExpExecArray | null;

  while ((match = exportPattern.exec(sourceCode)) !== null) {
    exports.push(`${match[1]}(${match[2]})`);
  }

  return exports;
}

/**
 * Generates a test block for a given function signature.
 */
function generateTestBlock(
  funcSignature: string,
  framework: string,
  includeEdgeCases: boolean
): string {
  const funcName = funcSignature.split("(")[0].trim();
  const itFn = framework === "mocha" ? "it" : "it";

  const edgeCases = includeEdgeCases
    ? `
  ${itFn}("should handle empty input gracefully", () => {
    // TODO: test with empty/null/undefined inputs
    expect(() => ${funcName}()).not.toThrow();
  });

  ${itFn}("should handle invalid input types", () => {
    // TODO: verify type guards or error handling
    expect(() => ${funcName}(null as any)).not.toThrow();
  });
`
    : "";

  return `describe("${funcName}", () => {
  ${itFn}("should be defined", () => {
    expect(${funcName}).toBeDefined();
  });

  ${itFn}("should return the expected output for valid input", () => {
    // TODO: replace with realistic input and expected output
    const result = ${funcName}();
    expect(result).toBeDefined();
  });
${edgeCases}});
`;
}

/**
 * Main skill function: generates unit tests for the provided TypeScript source.
 */
export async function generateTests(
  input: GenerateTestsInput
): Promise<GenerateTestsOutput> {
  const {
    sourceCode,
    filePath = "module.ts",
    framework = "jest",
    includeEdgeCases = true,
  } = input;

  const baseName = path.basename(filePath, path.extname(filePath));
  const testFileName = `${baseName}.test.ts`;
  const exports = extractExports(sourceCode);

  if (exports.length === 0) {
    return {
      testCode: `// No exported functions found in ${filePath}\n`,
      testFileName,
      testCount: 0,
    };
  }

  const importPath = `./${baseName}`;
  const importNames = exports.map((e) => e.split("(")[0]).join(", ");

  const header = [
    `/**`,
    ` * Auto-generated tests for ${baseName}`,
    ` * Framework: ${framework}`,
    ` * Generated by stitch-skills/generate-tests`,
    ` */`,
    ``,
    `import { ${importNames} } from "${importPath}";`,
    ``,
  ].join("\n");

  const testBlocks = exports
    .map((sig) => generateTestBlock(sig, framework, includeEdgeCases))
    .join("\n");

  const testCode = header + testBlocks;

  return {
    testCode,
    testFileName,
    testCount: exports.length * (includeEdgeCases ? 3 : 1),
  };
}
